### ISSUE TITLE
Waypoint type "canyon" is missing

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_common#14]
in https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L17-L55

**Comment by tsauerwein** [comment]
The migration script also has to be adapted: https://github.com/c2corg/v6_api/blob/master/c2corg_api/scripts/migration/documents/waypoints/summit.py#L79

**Comment by asaunier** [comment]
Transfered to #15
