### ISSUE TITLE
Use DEFAULT_* for routes attributes

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_common#3]
Use DEFAULT_FIELDS, DEFAULT_REQUIRED, etc. in https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_route.py as we did for waypoints: https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_waypoint.py

**Comment by tsauerwein** [comment]
I pushed my changes.

**Comment by asaunier** [comment]
Thanks, I think I'll do this task this afternoon.
