### ISSUE TITLE
Add condition in API result

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_common#51]
I would add condition in card of outings. If I understand I have to add "rating_condition" in DEFAULT_LISTING in https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_outing.py#L51

How to test ? (no need to install full api ?)

**Comment by asaunier** [comment]
Changes are needed in the API, at least to make it include the new version of https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_outing.py

It's not possible to test the change without a test API.

**Comment by stef74** [comment]
Ok I try to install it this week-end

**Comment by asaunier** [comment]
What you plan to do is not difficult:
* add ``condition_rating`` to https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_outing.py#L51
* update the new c2corg_common commit hash at https://github.com/c2corg/v6_api/blob/master/requirements.txt#L51 (doing so in the UI makes sense as well)
* upgrade the modules using ``make upgrade``

Indeed, setting the API up will most likely be the longest part.

**Comment by asaunier** [comment]
PR https://github.com/c2corg/v6_common/pull/54 and https://github.com/c2corg/v6_api/pull/643 make the ``condition_rating`` attribute available in the outings lists.

**Comment by asaunier** [comment]
@stef74 Closing the issue since the PRs have been merged.
