### ISSUE TITLE
Distinguish translation for snow quality and quantity ratings

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/v6_common#64]
See https://github.com/c2corg/c2c_ui/issues/570 and https://github.com/c2corg/c2c_ui/pull/571

* [x] Add snow_quality_ratings and snow_quantity_ratings
* [ ] Move data key-values from python to json

**Comment by tristan0x** [comment]
Hey @cbeauchesne 
I was thinking of taking care of c2corg/v6_api#816 and I am wondering if dedicated constants should also be added in `c2corg_common/sortable_search_attributes.py`.

Besides, what about reusing in `c2corg_common/sortable_search_attributes.py` the constants defined in `c2corg_common/attributes.py` to prevent duplication like below?

```
diff --git a/c2corg_common/sortable_search_attributes.py b/c2corg_common/sortable_search_attributes.py
index b5b4c3a..b32b3d6 100644
--- a/c2corg_common/sortable_search_attributes.py
+++ b/c2corg_common/sortable_search_attributes.py
@@ -301,6 +301,13 @@ sortable_condition_ratings = {
     'awful': 4
 }

+def _build_attr(enum):
+    return dict((p[1], p[0]) for p in enumerate(enum))
+
+sortable_snow_quality_ratings = _build_attr(attributes.snow_quality_ratings)
+
+sortable_snow_quantity_ratings = _build_attr(attributes.snow_quantity_ratings)
+
```

**Comment by asaunier** [comment]
The topic is old to me, I hope I don't write stupid things :P 

In the API those ratings are used for instance in the outing model:
https://github.com/c2corg/v6_api/blob/3a5d5202da0ee49903b7ce495e141c41dce27892/c2corg_api/models/outing.py#L67-L71

Those 3 fields use the same enum defined at https://github.com/c2corg/v6_api/blob/cdfae838eca974a06b0610f715e19f05f451364e/c2corg_api/models/enums.py#L107-L108
coming from https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L529-L535

I see ``snow_quality_ratings`` or ``snow_quantity_ratings`` used nowhere?!

It would make then to change this.
A problem though: those enums are "string" values, directly saved to postgres tables:
```
c2corg=# select condition_rating, snow_quantity, snow_quality from guidebook.outings where snow_quality is not null limit 10;
 condition_rating | snow_quantity | snow_quality 
------------------+---------------+--------------
 excellent        | average       | excellent
 excellent        | excellent     | excellent
 good             | good          | good
 good             | average       | excellent
 good             | good          | good
 good             | average       | good
 average          |               | poor
 good             | average       | good
 good             | good          | good
 average          |               | average
(10 rows)
```
If we plan to change the values (do we?), we'll have to make an alembic script run to update all existing outings...

**Comment by cbeauchesne** [comment]
@saunier, Actually, as the values are saved as string in DB, do we need to make a migration ? 

> I am wondering if dedicated constants should also be added in c2corg_common/sortable_search_attributes.py.

Yes, I miss them sorry

> Besides, what about reusing in c2corg_common/sortable_search_attributes.py the constants defined in c2corg_common/attributes.py to prevent duplication like below?

I agree with the goal of avoiding duplication. But, those constants are loaded by the UI, with a terrible hack that mix python and JS => I plan to move all these constants to a JSON format, so no, simply stick to the (perfectible) model. I'll do a big revamp on this repo.

**Comment by asaunier** [comment]
> Actually, as the values are saved as string in DB, do we need to make a migration ?

@cbeauchesne I would say yes as the table definitions in postgres actually use those enums explicitly. See the last rows of
<img width="487" alt="Capture d’écran 2020-11-16 à 23 27 59" src="https://user-images.githubusercontent.com/1192331/99315840-944ed600-2863-11eb-847b-1283ae8be0db.png">

**Comment by cbeauchesne** [comment]
Good catch!

@tristan0x may be not the best choice, so. And for the record, it'll make absolutely no difference on UI side, it was more a translation issue. We'll need to fix it one day, for the clarity of the code, but it's not urgent.

I recommand choosing another one :)
